"""Reviewed translations of the accepted six-paper symbol context, without edits to sources."""
TEXT = {
 'AppendixC(1)固定分量':'Fixed component in Appendix C (1)',
 'AppendixC(2)固定OR分量':'Fixed OR component in Appendix C (2)',
 'B.5–B.7证明工具':'Proof tools in B.5–B.7',
 'Section2.1整体模型；固定原样本x':'The whole model in Section 2.1; fixed original sample x',
 'Theorem3/固定整体模型g':'Theorem 3 / fixed whole-model game g',
 'X；Taylor部分X=ℝⁿ':'X; X=ℝⁿ in the Taylor section',
 'ℕ，相关对数/矩阵段n>M≥1':'Natural numbers; n>M≥1 in the relevant logarithm / matrix argument',
 'ℝⁿ或对应输入域':'ℝⁿ or the corresponding input domain',
 '与输入坐标同型的向量':'Vector with the same coordinate type as the input',
 '交互S':'Interaction S','全局':'Global','全局；D.2记Iand':'Global; denoted I_and in D.2',
 '公共库':'Shared library',
 '各公式内哑变量/目标集合须区分':'Distinguish bound variables from the target set within each formula',
 '各求和式的绑定范围':'Binding scope of each sum','固定分解':'A fixed decomposition',
 '固定模型':'A fixed model','固定模型的掩码规则':'Masking rule of the fixed model',
 '当前选定变量':'The currently selected variables','掩码 / Taylor':'Masking / Taylor expansion',
 '掩码与交互':'Masking and interactions','某样本第i变量':'Variable i of a particular sample',
 '某模型与某样本':'A particular model and sample','某次交互提取':'One interaction extraction',
 '论文全局':'Global within the paper',
 '跨论文对照；本篇公式未先中心化':'Cross-paper correspondence; this paper formula is not centered first',
 '输入向量；原文n个变量':'Input vector; the source has n variables',
 '输入域X到实数':'Input domain X to the real numbers',
 '有限集合':'Finite set','自然数':'Natural number','实数':'Real number',
 'ℝ或输入变量域':'The real numbers or the input-variable domain',
 'ℕ；Lemma3有1≤M<n':'Natural numbers; Lemma 3 requires 1≤M<n',
 'ℝ，0≤m≤n':'Real numbers, with 0≤m≤n',
 '正实数；0/0边界原文未定义':'Positive real numbers; the source leaves the 0/0 boundary undefined',
 'ℝ；分母0时数学比例未定义':'Real numbers; the mathematical ratio is undefined when the denominator is zero',
 '正实数':'Positive real number','ℝ；最大值非零时':'Real numbers, when the maximum is nonzero',
 '非负实数':'Nonnegative real number',
 '整数（i≥1）或实数（i=0）':'Integers for i≥1, or real numbers for i=0',
 'ℕⁿ子集':'Subset of ℕⁿ','ℝ；需相应阶可微':'Real numbers; differentiability of the relevant order is required',
 'ℝ或随机变量':'Real numbers or random variables','正整数':'Positive integer',
 'ℝ，可正可负或零':'Real numbers, positive, negative or zero',
 '模型及各前缀偏导→实值函数':'Model and its successive prefix derivatives to real-valued functions',
 '实值函数→实值函数':'Real-valued functions to real-valued functions',
 '由2^N→ℝ的f和T得到新游戏':'A new game obtained from f:2^N→ℝ and T',
 '有限子集族':'Finite family of subsets','ℝ；原分母须非零':'Real numbers; the original denominator must be nonzero',
 '2^n×m实矩阵':'2^n×m real matrix','实矩阵→非负向量':'Real matrices to nonnegative vectors',
 '概率空间→ℝ':'Probability space to the real numbers','实数；分母非零时':'Real numbers, when the denominator is nonzero',
 '实值有限集合函数→实值有限集合函数':'Real-valued finite-set functions to real-valued finite-set functions',
 '固定一个模型；输入域按论文与模型单列':'A fixed model; its input domain is recorded separately for each paper and model',
 '固定模型的一次输入':'One fixed input to a fixed model','当前所选输入变量':'The currently selected input variables',
 '当前有限总体N':'The current finite universe N','当前公式的绑定范围':'Binding scope of the current formula',
 '固定掩码规则':'A fixed masking rule','固定x,r,N':'Fixed x, r and N','固定v,x,r,N':'Fixed v, x, r and N',
 '固定模型与样本':'A fixed model and sample','由当前g显式构造':'Explicitly constructed from the current g',
 '固定实值集合函数g':'A fixed real-valued set function g','固定样本':'A fixed sample',
 '中心化集合函数g₀':'The centered set function g₀','平均输出 / 下界':'Mean output / lower bound',
 'A^(k)及组合矩阵':'A^(k) and the combinatorial matrix',
 '固定总体、模型与掩码标签':'A fixed universe, model and mask labels','指定AND分量游戏':'The specified AND-component game',
 'Section2.1整体模型的OR变换':'OR transform of the whole model in Section 2.1',
 '指定总体N与OR分量游戏':'The specified universe N and OR-component game',
 '固定当前分量f与保留标签T':'The fixed current component f and retained label T',
 '某模型/交互类型':'A particular model / interaction type','固定阈值/模型/类型':'A fixed threshold / model / type',
 '多模型优化与Definition1':'Multi-model optimization and Definition 1',
 '同一语义变量总体的m个模型':'m models with the same semantic variable universe',
 'Definition1某模型/类型':'A particular model / type in Definition 1','模型i与掩码T':'Model i and mask T',
 '跨模型优化':'Cross-model optimization','模型i':'Model i','模型i与数据分布':'Model i and the data distribution',
 '按子集行、模型列':'Subset-indexed rows and model-indexed columns','Eq5,6定义':'Definitions in Eqs. (5) and (6)',
 'Eq6和AppendixI':'Eq. (6) and Appendix I','固定模型/样本；随机性来自输出噪声':'A fixed model / sample; randomness comes from output noise',
 'AppendixD IID模型':'The IID model in Appendix D','鲁棒优化参数':'Robust-optimization parameter',
 '模型i/样本x':'Model i / sample x','公共父概念':'Shared parent concept',
 'i∈N，故n≥1':'i∈N, hence n≥1',
 'T⊆N；正阶k≥1是有效定义域核验，原文只称k-th未明写不等式；k=0不在本轮对齐范围':'T⊆N; positive order k≥1 is the checked valid-domain interpretation. The source only says kth order, without an explicit inequality; k=0 lies outside the checked alignment.',
 '当前STI闭式核验采用正整数阶数 $k>0$ 的有效定义域解释；CVPR原文仅写k-th，未显式写不等式；k=0没有计入已核验范围。':'The current STI closed-form check uses the valid-domain interpretation of positive integer order $k>0$. The CVPR source only says kth order, without an explicit inequality; k=0 is excluded from the verified scope.',
 '正确定义域p,q>0；原路线调用q=0非法':'The valid domain is p,q>0; the original argument illegally invokes q=0',
 '表达式分母>0；原文未明示零分母规则':'The expression has a positive denominator; the source states no zero-denominator convention',
 '经典偏导的使用需要真实存在；有限差分本身不需要可微。':'Classical partial derivatives must actually exist when used; finite differences themselves require no differentiability.',
 '输入与参数固定，所有集合为有限。':'The input and parameters are fixed, and all sets are finite.',
 '有限总体；所有掩码用同一分解。':'The universe is finite; every mask uses the same decomposition.',
 '有限S':'Finite S','不适用':'Not applicable',
 'n=0的代数边界允许；Shapley选i∈N时强制n≥1':'The algebraic n=0 boundary is allowed; choosing i∈N for Shapley attribution forces n≥1',
 'n=0时有唯一空掩码':'When n=0 there is one empty mask',
 '本篇子集和包括空集':'Subset sums in this paper include the empty set',
 'x空=r；xN=x':'x_empty=r; x_N=x','g空=b':'g(empty)=b',
 '空集交互等于b':'The empty interaction equals b','空集阶数0':'The empty set has order zero',
 '空掩码时所有Xi=0':'Every X_i is zero on the empty mask','空模式空积1':'The empty pattern has empty product one',
 '若空模式保留则空输入Y=b；删去空模式则可有基线误差':'If the empty pattern is retained, Y=b on the empty input; deleting it can introduce baseline error',
 '可含空模式；Omega本身也可为空':'Empty patterns are allowed; Omega itself may also be empty',
 'd空=g空':'d(empty)=g(empty)','I_gi空=g(i)，不是原基线b':'I_gi(empty)=g({i}), which differs from the original baseline b',
 'π空=空':'π(empty)=empty','A空时uA为常数c；唯一空交互c':'If A is empty, u_A is the constant c; its only interaction is the empty interaction c',
 'T空时等于g(S)；S空时等于I_g(T)':'For empty T this equals g(S); for empty S it equals I_g(T)',
 '环境S可空；w空不分给i':'The environment S may be empty; the empty dividend is not allocated to i',
 '原T⊆N量词允许T空；采用公式的空目标延伸，基线b参与':'The original quantifier T⊆N allows empty T; the formula is extended to that empty target and includes baseline b',
 'T空、k>0属低阶分支，值b；N空仍成立':'Empty T with k>0 belongs to the lower-order branch and has value b; the identity also holds for empty N',
 'L空必须保留，不可套用原非法Beta零参数':'Empty L must be retained; the original invalid zero-parameter beta argument cannot be applied',
 '含空掩码；完整权重必0，截断权重不必0':'Includes the empty mask; its complete weight is zero, while its truncated weight need not be zero',
 'Omega空且gN=0时原定义0/0未给约定':'If Omega is empty and g(N)=0, the source supplies no convention for its 0/0 expression',
 '空子节点族积1':'The product of an empty child-node family is one','需α非空方可除其大小':'α must be nonempty before dividing by its size',
 'm=0时为0':'Zero when m=0','无k阶交互时分母可能为0':'The denominator may be zero when no order-k interaction exists',
 '若全零则分母0，原图规范未给该边界':'If all values are zero, the denominator is zero; the original plotting normalization gives no convention at this boundary',
 'Q_∅={0}，但作者候选I~(∅)单独定义0':'Q_empty={0}, but the author separately defines the candidate interaction I_tilde(empty)=0',
 'P_∅={0}':'P_empty={0}','Ior(∅)=0，空集不套非空公式':'I_or(empty)=0; the nonempty-set formula is not used at the empty set',
 'gand(∅)=0':'g_and(empty)=0','gor(∅)=0':'g_or(empty)=0',
 'γ∅=0由两分量空集0导出':'γ_empty=0 follows from the zero empty values of both components',
 '空列表有限差分为原函数；论文高阶目标非空。':'The finite difference for an empty list is the original function; the paper targets nonempty higher-order interactions.',
 '原矩阵列出全部2^n项，包括空集。':'The original matrix lists all 2^n entries, including the empty set.',
 '原I(empty)=0；原始g(empty)不默认零；空场R1/R2可为常数，实际无偏置架构恒零。':'The source defines I(empty)=0; raw g(empty) is not assumed zero. R1/R2 allow a constant empty field, whereas the actual bias-free architecture is identically zero there.',
 '按相关定义与已登记问题解释。':'Interpret using the relevant definitions and recorded issues.',
 '不省略空集作用域；使用相关条目的显式约定。':'Keep the empty-set scope and use the explicit convention of the relevant entry.',
 '原AND/OR公式只对非空交互；分量空输出单独保留。':'The original AND/OR formulas concern nonempty interactions; each component empty output is retained separately.',
 '固定输入基线r；不假定输出基线为0':'The input baseline r is fixed; the output baseline is not assumed zero',
 'ε∅随中心化扣除，不应默认零':'ε_empty is subtracted during centering and must not be assumed zero',
 '输入基线r任意；非空中心化交互等于原始交互。':'The input baseline r is arbitrary; nonempty centered interactions equal the raw interactions.',
 '各分量空集值不默认0。':'Component empty values are not assumed zero.',
 '原输入b_i映射r_i；原V=g0；原I=I_g0；输出b=g(empty)。':'Original input b_i maps to r_i; original V=g0 and original I=I_g0; output baseline b=g(empty).',
 '输入基线r与输出基线g(empty)分别保留。':'The input baseline r and output baseline g(empty) are retained separately.',
 '原始输出基线不默认零；输入基线向量与分类器截距单独标识。':'The raw output baseline is not assumed zero; the input-baseline vector and classifier intercept are identified separately.',
 'g(空集)=b，a(空集)+o(空集)=b，不默认零。':'g(empty)=b and a(empty)+o(empty)=b; these values are not assumed zero.',
 '不默认f(∅)=0':'f(empty) is not assumed zero',
 'Theorem3所在Case1排除完全抵消；Case2不能统一用零除法。':'Case 1 containing Theorem 3 excludes complete cancellation; Case 2 cannot be handled by silently dividing by zero.',
 'p16 Eq10的|max(a,b)|不等于p6定义max(|a|,|b|)，原等价式有反例。':'The signed |max(a,b)| in page 16 Eq. (10) differs from max(|a|,|b|) defined on page 6; the asserted equivalence has a counterexample.',
 'δ^(k)为临时每阶偏移，与共同δ另有最大值关系。':'The temporary order-specific offset δ^(k) is related by a maximum to the common offset δ.',
 'ξ与输入坐标xi不同。':'ξ differs from input coordinate x_i.',
 '与Beta函数临时参数p是不同概念。':'This differs from the temporary beta-function parameter p.',
 '原b表示输入基线向量；规范b专指v(x_∅)。':'Original b is the input-baseline vector; canonical b denotes only v(x_empty).',
 '原文未去噪句两次写uand；去噪gor同写+γ与分解和不符，作为证明/算法式问题记录。':'The source non-denoising sentence writes u_and twice; its denoising g_or also uses +γ, inconsistent with the decomposition sum. Both are recorded as proof/algorithm-expression issues.',
 '原无上标λ与λ^(k)不同。':'The original unsubscripted λ differs from λ^(k).',
 '正式p22写(1−x)^(1−q)，与后续阶乘式不一致；正确工具定义只用于已授权证明修复，原式保真。':'Formal page 22 writes (1−x)^(1−q), inconsistent with the later factorial formula. The correct auxiliary definition is used only in the authorized proof correction; the original expression is preserved.',
 '经验图使用严格>，定理计数使用≥；边界必须保留。':'Empirical plots use strict > while the theorem count uses ≥; the boundary distinction is preserved.',
 '规范q用于最高阶；原k在本节与A^(k)的阶指标不同。':'Canonical q denotes the highest degree; the local original k differs from the order index in A^(k).',
 '须显式验证固定基线掩码合成后对原字面式证明；不能直接字符串改为固定x。':'Prove the literal source expression after explicitly verifying fixed-baseline mask composition; it cannot be replaced by fixed x through a string substitution.',
 'CNN局部核维数CK²；不把MLP全前层宽度作为该来源定义。':'The CNN local kernel dimension is CK²; the full preceding MLP-layer width is not substituted for this source definition.',
 'groupgate与scalarAND数值不同；其余按显式定义对齐。':'The group gate and scalar AND gate have different values; the remaining correspondence follows the explicit definitions.',
 '保留源定义域和中心化约定。':'Preserve the source domain and centering convention.',
 '原b_i对应公共输入基线向量r的第i坐标r_i；不是输出基线标量b。':'Original b_i corresponds to coordinate r_i of the shared input-baseline vector r; it differs from scalar output baseline b.',
 '原局部符号和定义域保留。':'Preserve the original local notation and domain.',
 '模型输出g与block线性值g_u作用域不同。':'Model output g and block linear value g_u have different scopes.',
}

def translate_context(value):
 if isinstance(value,str):return TEXT.get(value,value)
 if isinstance(value,list):return [translate_context(x) for x in value]
 return value
