from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parent

# These counts describe inspected PDF structure, not mathematical correctness.
# Actual proof passages are separate from distinct numbered result declarations.
MANUAL={
 '2207.11694':dict(recommendation='recommend',topic='adversarial transferability / game interactions',proof_count=36,proof_count_kind='manual_lower_bound',numbered_result_count=37,numbered_result_inventory='Theorems 1–3; Propositions 1–9; Lemmas 1–20; Corollaries 1–5. Includes cited standard Lemmas 5, 6, 16, whose proofs are not supplied here.',proof_pages_or_span={'span':[25,93],'kind':'proof-bearing appendix span, includes setup and equations'},proof_evidence=[{'section':'Appendices A.2–A.4, B–N','pdf_pages':[25,93],'identifiers':'3 theorems, 9 propositions, 20 lemmas, 5 corollaries','detail':'Repeated main/appendix statements counted once. 34 numbered results have local proof passages; 3 standard cited lemmas excluded from local proof count. At least 2 additional unnumbered derivations (pairwise equivalence and p-interaction sum).'}],rationale='97页技术报告含连续大篇幅解析证明，是本轮最明显的证明丰富遗漏；与2010.04055有前期/扩展关系，两篇应分别保留版本并由用户决定收录。'),
 '2205.15130':dict(recommendation='recommend',topic='adversarial training / Hessian dynamics',proof_count=12,proof_count_kind='manual_lower_bound',numbered_result_count=12,numbered_result_inventory='Main Theorems 1–6; main Lemma 1; Appendix Lemmas 2–5; Corollary 1. Appendix Theorem 7 restates main Theorem 5 and is not counted again.',proof_pages_or_span={'span':[12,31],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'Appendices A–H.2','pdf_pages':[12,31],'identifiers':'Theorems 1–5; Lemmas 1–5; Corollary 1; Assumption 2','detail':'Inspected the actual derivations and proof starts. Bound counts theorem/lemma proofs plus the separate Assumption 2 and training-strength derivations conservatively; Theorem 6 does not add an appendix proof to this bound.'}],rationale='首次公开2022，个人列表后改名Clarifying the Behavior and the Difficulty of Adversarial Training (AAAI2024)；预印本已有大量解析证明。'),
 '2205.15146':dict(recommendation='recommend',topic='batch normalization / derivatives',proof_count=12,proof_count_kind='manual_exact_proof_blocks',numbered_result_count=7,numbered_result_inventory='Theorems 1–3; Lemmas 1–3; Corollary 1.',proof_pages_or_span={'span':[13,25],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'Appendices C, D.1–D.4, E–H','pdf_pages':[13,25],'identifiers':'Theorems 1–3; Lemmas 1–3; Corollary 1','detail':'C contains a preliminary Taylor derivation plus 3 lemma proofs; D contains 3 theorem proofs plus 1 corollary proof; E–H contain 4 additional named derivations/proofs. Counts are 12 actual blocks, not 12 theorems.'}],rationale='非Harsanyi方向但证明密度高；正式AAAI2024版本作者名单有新增，当前固定为2022v2。'),
 '2210.09020':dict(recommendation='recommend',topic='frequency representation / convolutional decoder',proof_count=9,proof_count_kind='manual_lower_bound',numbered_result_count=8,numbered_result_inventory='Theorems 3.2, 4.2–4.5; Corollaries 3.3–3.4; Lemma A.1. Assumption 4.1 has a separate derivation and is not counted as a theorem.',proof_pages_or_span={'span':[11,25],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'Appendices A.1–A.7; preliminary Lemma A.1','pdf_pages':[11,25],'identifiers':'Theorems 3.2, 4.2, 4.3, 4.4, 4.5; Corollaries 3.3, 3.4; Lemma A.1','detail':'Actual proof passages start on PDF11,12,14,15,18,19,21,22,23,24. Multiple parts for Theorem 4.2 are treated conservatively as one result proof; at least 9 proof units including the Assumption 4.1 derivation.'}],rationale='2022首次预印本、ICML2023正式论文；34页中附录15页连续推导，证明丰富且主题不限于交互。'),
 '2111.06206':dict(recommendation='recommend',topic='Harsanyi / sparse concepts / attribution',proof_count=12,proof_count_kind='manual_exact_distinct_proof_units',numbered_result_count=5,numbered_result_inventory='Theorems 1–5. Main-text and appendix restatements counted once.',proof_pages_or_span={'span':[14,23],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'C','pdf_pages':[14,15],'identifiers':'Theorem 1 (faithfulness and uniqueness)','detail':'Necessity and sufficiency are two parts of one proof, counted once.'},{'section':'D.1','pdf_pages':[15,18],'identifiers':'7 unnumbered axioms: efficiency, linearity, dummy, symmetry, anonymity, recursive, interaction distribution','detail':'Seven separate property proof units; not seven theorems.'},{'section':'D.2','pdf_pages':[18,23],'identifiers':'Theorems 5, 2, 3, 4','detail':'4 distinct theorem proofs connecting marginal benefits, Shapley values, Shapley interaction, Shapley-Taylor interaction.'}],rationale='已有v6正式archive仍须在新清单中完整展示：38页、5独立编号定理、12类实际证明；不能按旧库存仅三论文概括实验室。'),
 '2103.07364':dict(recommendation='recommend',topic='adversarial robustness / multiorder interactions',proof_count=15,proof_count_kind='manual_lower_bound',numbered_result_count=1,numbered_result_inventory='Proposition 1 (equivalence with conditional mutual information).',proof_pages_or_span={'span':[16,23],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'B.1–B.4','pdf_pages':[16,20],'identifiers':'5 interaction properties; 4 multiorder Shapley properties; 2 connections; Proposition 1 plus converse derivation','detail':'13 actual proof blocks inspected, mostly unnumbered properties.'},{'section':'D, G','pdf_pages':[21,22],'identifiers':'meaning of ΔI; attribution detector utility','detail':'2 additional explicit proof blocks. H (PDF22–23) contains dropout derivation but is not included in the lower bound.'}],rationale='27页预印本核心方法附录证明多但编号少；2111.03536官方明确为误申新ID，应并到本ID。'),
 '2105.10719':dict(recommendation='recommend',topic='Shapley baseline / masked states / Harsanyi',proof_count=7,proof_count_kind='manual_exact_distinct_proof_units',numbered_result_count=4,numbered_result_inventory='Theorems 1–4. Theorems 3 and 4 share a joint proof with Remark 2.',proof_pages_or_span={'ranges':[[17,20],[29,30]],'kind':'proof-bearing appendix ranges'},proof_evidence=[{'section':'E.1–E.3, F','pdf_pages':[17,20],'identifiers':'Theorems 1,2; joint Remark 2 / Theorems 3,4; masked-variable property','detail':'4 distinct proof units; joint proof is counted once.'},{'section':'end of G.10 / appended analytic derivations','pdf_pages':[29,30],'identifiers':'Equations 9,10,11: multilevel Shapley decomposition and Harsanyi connections','detail':'3 separate explicit proof blocks.'}],rationale='2021首次预印本后来ICLR2023，官网旧名Learning Baseline Values for Shapley Values与新标题同ID；附录含7独立证明单元。'),
 '2010.04055':dict(recommendation='recommend',topic='adversarial transferability / Shapley interaction',proof_count=8,proof_count_kind='manual_lower_bound',numbered_result_count=7,numbered_result_inventory='Propositions 1–3; Lemmas 1–4.',proof_pages_or_span={'ranges':[[17,20],[23,31]],'kind':'proof-bearing appendix ranges'},proof_evidence=[{'section':'D–I','pdf_pages':[17,31],'identifiers':'Propositions 1–3; Lemmas 1–4; equivalence derivation in G','detail':'7 distinct numbered local proofs and at least 1 unnumbered equivalence proof. Restated propositions counted once.'}],rationale='ICLR2021论文35页预印本附录大量解析证明；是2207.11694的明确前期版本，但有独立正式会议身份。'),
 '2205.01940':dict(recommendation='recommend',topic='representation complexity / information theory / disentanglement',proof_count=10,proof_count_kind='manual_exact_proof_blocks',numbered_result_count=0,other_numbered_properties=3,numbered_result_inventory='No Theorem/Lemma/Proposition/Corollary declarations; numbered Properties 1–3 contain multiple separately proved inequalities.',proof_pages_or_span={'span':[13,15],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'B.1–B.4','pdf_pages':[13,15],'identifiers':'Properties 1–3 and 3 information/disentanglement relations','detail':'Actual Proof blocks: PDF13 has 3, PDF14 has 4, PDF15 has 3. Three proof blocks under a property are not counted as three numbered theorems.'}],rationale='ICML2022正式理论论文，虽无Theorem编号但有10个显式证明段，不能被定理关键词计数漏掉。'),
 '2112.00980':dict(recommendation='recommend',topic='feature diversity / MLP learning dynamics',proof_count=5,proof_count_kind='manual_lower_bound',numbered_result_count=5,numbered_result_inventory='Theorems 1–2; Lemmas 1–3.',proof_pages_or_span={'ranges':[[26,29],[31,34]],'kind':'proof-bearing appendix ranges'},proof_evidence=[{'section':'E, F, H.1, K, L','pdf_pages':[26,33],'identifiers':'Lemma 1, Lemma 2, Theorem 1, Lemma 3, Theorem 2','detail':'5 distinct local result proofs, with main/appendix restatements collapsed. M (PDF33–34) also derives the momentum effect but is not included in the lower bound.'}],rationale='35页预印本中5独立编号结果及多页证明；没有正式会议记录也不能因此自动漏掉。'),
 '2111.06236':dict(recommendation='secondary',topic='representation bottleneck / multiorder interactions',proof_count=2,proof_count_kind='manual_exact_distinct_proof_units',numbered_result_count=2,numbered_result_inventory='Theorems 1–2.',proof_pages_or_span={'span':[16,17],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'B.1–B.2','pdf_pages':[16,17],'identifiers':'Theorem 1 (training strength), Theorem 2 (output-change decomposition)','detail':'Inspected the actual derivation in B.1 and B.2; no extra independent theorem counted from repeats.'}],rationale='ICLR2022核心相关论文，但此版只有2个独立定理证明；可列次级供用户决定，不以相关性代替证明数量。'),
 '2006.13016':dict(recommendation='recommend',topic='rotation equivariance / privacy protection',proof_count=7,proof_count_kind='manual_exact_distinct_proof_units',numbered_result_count=0,numbered_result_inventory='Unnumbered operation-level derivations.',proof_pages_or_span={'span':[11,13],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'A.1, A.2, A.3.1–A.3.5','pdf_pages':[11,13],'identifiers':'d-ary convolution; componentwise processing; convolution, ReLU, BN, pooled Avg/Max/Dropout, skip-connection equivariance','detail':'2 signal-processing derivations plus 5 layer-type equivariance proofs. Avg/Max/Dropout share one proof and are counted once.'}],rationale='20页早期组论文并非交互主题，却有7类实际代数证明，应纳入广义证明候选。'),
 '1911.09040':dict(recommendation='secondary',topic='quaternion / rotation equivariance / point clouds',proof_count=4,proof_count_kind='manual_exact_distinct_proof_units',numbered_result_count=0,numbered_result_inventory='Unnumbered operation-level derivations.',proof_pages_or_span={'span':[19,20],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'C.1–C.4','pdf_pages':[19,20],'identifiers':'convolution, ReLU, batch normalization, max-pooling equivariance','detail':'4 distinct explicit algebraic proofs; later elementwise pooling formulation D is not an additional proof.'}],rationale='ECCV2020正式论文，4类代数证明；与TPAMI2024 journal extension应建立扩展关系，不凭标题混成一篇。'),
 '2009.11729':dict(recommendation='secondary',topic='dropout / game interactions',proof_count=4,proof_count_kind='manual_lower_bound',numbered_result_count=0,numbered_result_inventory='Equation/property derivations, no numbered theorem declarations.',proof_pages_or_span={'span':[12,15],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'B, C, D','pdf_pages':[12,15],'identifiers':'Equations 4, 5, 6-left; approximated interaction-loss trustworthiness','detail':'B contains one decomposition proof, C has two equation proofs, D has one multi-page trustworthiness proof. Section A states 4 standard Shapley properties without local proofs; they are not counted.'}],rationale='ICLR2021相关论文，至少4个实际推导证明；理论note/正文共有性质的重复不当作新增定理。'),
 '2108.02646':dict(recommendation='secondary',topic='aesthetic appreciation / Harsanyi interaction',proof_count=3,proof_count_kind='manual_exact_distinct_proof_units',numbered_result_count=0,numbered_result_inventory='Unnumbered proofs of Equations 1, 3, 5.',proof_pages_or_span={'span':[15,17],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'A, B, D','pdf_pages':[15,17],'identifiers':'closed form multivariate interaction; classification-utility decomposition; Equation 5','detail':'Three explicit proof blocks. Appendix C only introduces Shapley values.'}],rationale='22页预印本有3个证明单元，主题相关但证明量不属最高梯队；保留次级。'),
 '2108.06895':dict(recommendation='secondary',topic='adversarial attribution / interactions',proof_count=2,proof_count_kind='manual_lower_bound',numbered_result_count=0,numbered_result_inventory='Unnumbered axiom proofs.',proof_pages_or_span={'span':[11,13],'kind':'proof-bearing appendix span'},proof_evidence=[{'section':'A–B','pdf_pages':[11,13],'identifiers':'linearity and efficiency of approximated pixel attribution','detail':'Two explicit proof paragraphs on PDF11; B adds interaction approximation derivations not included in lower bound.'}],rationale='ICCV2021公开PDF含附录；有证明但密度低于主推荐，不能仅凭“Interactions”题目升为高密度。'),
}

EXCLUDED={
 '2203.14101':('withdrawn_by_authors','官方arXiv说明作者因critical issues撤回；本轮不把作者撤回理由改写成数学错误判断。'),
 '2111.03536':('duplicate_author_confirmed','官方arXiv说明误申新ID，previous=2103.07364；合并到2103.07364。'),
 '2107.08821':('edited_proceedings_html_not_individual_paper','ICML2021 workshop proceedings仅提供HTML/HTML source，不是组员共同署名的独立研究论文；不能将合集证明归给作者。'),
 '1901.08813':('edited_proceedings_html_not_individual_paper','AAAI2019 workshop proceedings仅提供HTML/HTML source，不是组员共同署名的独立研究论文；不能将合集证明归给作者。'),
}

def main(output_name='papers.json'):
    acqs=json.loads((ROOT/'acquisition-index.json').read_text());papers=[]
    for a in acqs:
        i=a['arxiv_id']
        hits=a.get('automatic_heading_hits',[])
        p={'title':a['title'],'year':int(a['first_public_date'][:4]),'first_public_date':a['first_public_date'],
           'authors':a['authors'],'authors_evidence':{'source':a['source_url'],'pdf_page':1,'index':'publication-index/arxiv-author-earlier.json','note':'Author-index query is a discovery source; PDF first-page identity checked for manually reviewed candidates.'},
           'source_url':a['source_url'],'pdf_url':a['pdf_url'],'version':'arXiv:'+i+a['version'],
           'local_pdf':a.get('local_pdf'),'sha256':a.get('sha256'),'total_pages':a.get('total_pages'),
           'proof_evidence':[],'proof_count_kind':'not_counted_automatic_prescreen_only','proof_count':None,
           'numbered_result_count':None,'proof_pages_or_span':None,'topic':'pending manual classification',
           'recommendation':'uncertain','rationale':'已下载公开PDF并逐页抽取；自动命中只能用于定位，尚无人工完整证明清单，不能断言证明少。',
           'status':'automated_prescreen_pending_manual','duplicate_group':'arxiv:'+i,
           'automatic_screen':{'proof_or_derivation_keyword_line_hits':sum(bool(re.search(r'\b(?:Proof|proof|derivation|Derivation)\b',x['text'])) for x in hits),'numbered_result_keyword_line_hits':sum(bool(re.search(r'\b(?:Theorem|Lemma|Proposition|Corollary)\s+[A-Z]?\.?\d',x['text'])) for x in hits),'kind':'estimate_locator_not_count_of_proofs','evidence':'papers/'+i+'/acquisition.json'},
           'journal_ref_from_arxiv':a['journal_ref']}
        if i in MANUAL:
            p.update(MANUAL[i]);p['status']='pdf_manually_reviewed_for_proof_structure_not_correctness'
        if i in EXCLUDED:
            p['status'],p['rationale']=EXCLUDED[i];p['recommendation']='low_priority'
            if i=='2111.03536':p['duplicate_group']='arxiv:2103.07364'
        if i=='2010.04055':p['related_extension']='arxiv:2207.11694'
        if i=='2207.11694':p['related_previous_publication']='arxiv:2010.04055'
        papers.append(p)
    (ROOT/output_name).write_text(json.dumps(papers,ensure_ascii=False,indent=2))
    print(output_name+' draft:',len(papers),'entries;',len(MANUAL),'manually inspected candidates')
if __name__=='__main__':main()
